sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # upload encrypted service account file. This files holds Google Cloud access information
  - openssl aes-256-cbc -K $encrypted_4c5268da04fa_key -iv $encrypted_4c5268da04fa_iv -in k8s-service-acc.json.enc -out k8s-service-acc.json -d
  # Install Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # gCloud access authorization
  - gcloud auth activate-service-account --key-file k8s-service-acc.json
  # Declare gCloud project, zone & cluster in use
  - gcloud config set project fibonacci-k8s-app
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials fibonacci-app-cluster
  # Login docker hub account from travis
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Build all developer images for testing
  - docker build -t varxmeh/client-test -f ./client/Dockerfile.dev ./client
  # - docker build -t varxmeh/server-test -f ./server/Dockerfile.dev ./server
  # - docker build -t varxmeh/worker-test -f ./worker/Dockerfile.dev ./worker
script:
  - docker run varxmeh/client-test npm test -- --coverage
  # - docker run varxmeh/server-test npm test
  # - docker build -t varxmeh/worker-test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
