sudo: required
services:
    - docker

before_install:
    # test builds before releasing
    # As only client has test, client dev image is created
    - docker build -t varxmeh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run varxmeh/react-test npm test -- --coverage

after_success:
    - docker build -t varxmeh/fibonacci-client ./client
    - docker build -t varxmeh/fibonacci-server ./server
    - docker build -t varxmeh/fibonacci-worker ./worker
    - docker build -t varxmeh/fibonacci-nginx ./nginx

    # Login to docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    # take these images & push to docker hub
    - docker push varxmeh/fibonacci-client
    - docker push varxmeh/fibonacci-server
    - docker push varxmeh/fibonacci-worker
    - docker push varxmeh/fibonacci-nginx
