version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    server:
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes:
            - /server/node_modules
            - ./server:/server
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
