version: '3'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '8080:80'
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /server/node_modules
            - ./server:/server
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /worker/node_modules
            - ./worker:/worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
